name: Test

on:
  - push

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"

      - name: Install Node.js dependencies
        run: |
          npm ci

      - name: Test code
        run: npm run zapier-test
